### ISSUE TITLE
Fedora-24-20160329.n.0 compose 'import complete' signal sent, but RPMs not imported

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/pdc-updater#10]
As I write this, the Fedora-24-20160329.n.0 is imported into PDC - it's visible at https://pdc.fedoraproject.org/compose/209/ with `imported date` shown as 2016-03-29 22:48:34 , and the `org.fedoraproject.prod.pdc.compose` fedmsg was sent out, message ID `2016-bc7b85bd-24f2-4bd7-826e-1baf2bf899c0`.

However, I cannot query RPMs related to this compose. Any kind of query to the `rpms` API endpoint with `compose=Fedora-24-20160329.n.1` as a query param returns nothing, and if you click any of the `rpms` links on the compose page, you get an empty page (e.g. https://pdc.fedoraproject.org/compose/209/rpms/Everything/x86_64/ ).

This is a major problem for us because the tool that decides whether to create release validation events for new composes relies on being able to query the packages in the compose from PDC. It's written on the assumption that it can do this shortly after the `org.fedoraproject.prod.pdc.compose` fedmsg is sent. If that's not a valid expectation, then there's a problem; I need a way to know when I *can* reliably query PDC for the RPMs in a new compose.

**Comment by ralphbean** [comment]
OK, hours later.. I check https://pdc.fedoraproject.org/compose/209/rpms/Cloud/x86_64/ and it looks like the rpms are there.  I think I know why:

See [this stretch of code](https://github.com/fedora-infra/pdc-updater/blob/develop/pdcupdater/handlers/compose.py#L136-L148).  First, we upload the images.  Then, we upload the rpms.  Those happen as two different steps.  The amount of data in the rpms step is quite large, so it likely takes a while.  We're probably hitting (another) race condition where the 'compose' gets created in PDC in the first step (when we import the images).. but then there is significant lag until the second step is complete and the rpms are available.

What we should probably do is add *another* messaging hook in the PDC webapp itself so that it broadcasts a new signal when rpms are imported.  Then, you can trigger jobs off of that.

**Comment by AdamWill** [comment]
Thanks. I've whacked fedfind with the [ugly workaround stick](https://www.happyassassin.net/cgit/fedfind/commit/?id=3bad7330c83db9f005daefa40355f5be2c80e3ec) for now. When this is fixed I'll undo that again...(note to self: when this is fixed, remember to undo that again!)
