### ISSUE TITLE
Consumer's topic can't be constructed for internal message topics

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/pdc-updater#24]
To listen to Brew messages using STOMP internally, I've been using the topic `/queue/Consumer.pdc-updater-prod.VirtualTopic.eng.brew.build.tag`. The issue is that I can't tell the consumer in pdc-updater to listen on that topic based on how the topics are currently constructed in `consumer.py`.

This is how they are currently constructed:
```
self.topic = [
    '.'.join([config['topic_prefix'], config['environment'], topic])
    for handler in self.handlers for topic in handler.topic_suffixes
]
```

Since the `topic_prefix` for the handler should be `/queue/Consumer.pdc-updater-prod.VirtualTopic.eng` and the `topic_suffix` is `brew.build.tag` (in #23), I am forced to provide an `environment` in the configuration even though the topic does not have one.

I will gladly make the code changes necessary to support this, but I don't know what approach you'd like to take to address this.

Thank you for your help.

**Comment by ralphbean** [comment]
We talked about this on jit.si today and came up with something like this:

```python
# Tell fedmsg to only notify us about topics that our handlers want.
self.topic = sum([
    handler.construct_topics(config)
    for handler in self.handlers    
], [])   
```

Basically, instead of hardcoding *how* the topic gets dynamically constructed, we'll create a method on the base handler that does that same construction, but which allows handlers to override how that is done.

In the case of our handler that wants to subscribe to a STOMP queue, then it can do it in a different way which does not use the fedmsg topic_prefix or environment configuration variables.

**Comment by mprahl** [comment]
#25 addresses this
